### PR TITLE
Fixes #67 by changing method names by postfixing 'Ice'

### LINKED ISSUE #67: Selection overrides built-in rangy methods
Selection.js sets several methods on the rangy.rangePrototype, some of which conflict with rangy's TextRange module.

If I had to guess, I'd assume that the ice code came first, but regardless, the method signatures are incompatible, and including this plugin breaks any usages of the rangy-provided moveStart and moveEnd.

### PR DESCRIPTION
**Pull request by dustyjewett**
moveStart and moveEnd are provided by rangy's TextRange module, but have a different signature (and functionality).  I've changed all prototype methods added by ice to use 'Ice' in their name, to ensure that they are future-proof.

### CODE REVIEW

**Comment by imdfl** [comment]
Hi,

What's the use case? When another version of Rangy is already included?

**Comment by dustyjewett** [comment]
Yes, we use rangy in our other ckeditor plugins.

**Comment by imdfl** [comment]
Hi, sorry for the huge delay in addressing this issue.
I think that changing the method names is not a good approach. It's better to encapsulate rangy in a namespace and then provide the encapsulated rangy as a parameter to modules that use it. The code change is significantly smaller this way and merges are easier. I'm going to do this around mid Jan. Thanks again for the attention and effort.

**Comment by imdfl** [comment]
Please see the last commits to dev/master. Hopefully this scopes Rangy well enough for your needs.

**Pull request closed without merging**
